apiVersion: v1
kind: Service
metadata:
  name: gamers-app
  namespace: default
spec:
  selector:
    app: gamers-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort
