replicaCount: 3
image:
  repository: rafaelmaciel84/final
  tag: stable
  pullPolicy: IfNotPresent
service:
  name: gamers-app
  type: LoadBalancer
  externalPort: 8080
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
